[package]
name = "portable-packer"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.228", features = ["derive"] }
thiserror = "2.0.20"
tokio = { version = "1.53.1", features = ["rt-multi-thread", "macros", "sync", "signal", "fs", "io-util"] }

[features]
default	= ["archlinux"]

# Meta feature flag for package list extraction
package-extract = []

# Meta feature flag for post processing
post-process = []

archlinux = ["package-extract", "post-process"]

[profile.release]
lto = true
